version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "frontend"
    assignees:
      - "YsraelMauricio"

  - package-ecosystem: "composer"
    directory: "/backend"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "backend"
    assignees:
      - "YsraelMauricio"

  - package-ecosystem: "docker"
    directory: "/infra"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "infra"
    assignees:
      - "YsraelMauricio"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "ci"
    assignees:
      - "YsraelMauricio"
